---
name: macOS build

on:
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'

      - name: Setup native-image
        run: |
          gu install native-image

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: "latest"

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: clojure -A:test

      - name: Install upx
        run: brew install upx

      - name: Build native-image
        run: clojure -A:native-image

      - name: Run upx
        run: upx fix-default-branch

      - uses: actions/upload-artifact@v2
        with:
          name: fix-default-branch-macos
          path: fix-default-branch
