---
name: Windows build

on:
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'

      - name: Setup Clojure manually
        run: .\.github\ClojureSetupHeadless.ps1

      # Uncomment this when it supports Windows:
      # https://github.com/DeLaGuardo/setup-clojure/issues/1
      #
      # - name: Setup Clojure
      #   uses: DeLaGuardo/setup-clojure@2.0
      #   with:
      #     tools-deps: "latest"

      # - name: Install VC2017 components
      #   # This is necessary for native-image in GraalVM JDK11. JDK8 is more complicated.
      #   run: >
      #     choco install visualstudio2017community
      #       --version 15.9.17.0
      #       --no-progress
      #       --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.ARM64
      #                             --add Microsoft.VisualStudio.Component.VC.CMake.Project"

      - name: Install native-image
        run: $env:GRAALVM_HOME\bin\gu.cmd install native-image

      - name: List GraalVM bin contents
        run: Get-ChildItem -Path "$env:GRAALVM_HOME\bin" | Format-Table

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: clojure -A:test

      - name: Build native-image
        run: clojure -A:native-image
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}

      - name: Install upx
        run: choco install upx

      - name: Run upx
        run: upx fix-default-branch

      - uses: actions/upload-artifact@v2
        with:
          name: fix-default-branch-win64
          path: fix-default-branch
