---
name: Windows build

on:
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'

      - name: Setup Clojure manually
        run: .\.github\ClojureSetupHeadless.ps1

      # Uncomment this when it supports Windows:
      # https://github.com/DeLaGuardo/setup-clojure/issues/1
      #
      # - name: Setup Clojure
      #   uses: DeLaGuardo/setup-clojure@2.0
      #   with:
      #     tools-deps: "latest"

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: clojure -A:test

      - name: Install upx
        run: choco install upx

      - name: Build native-image
        run: $env:GRAALVM_HOME="$env:JAVA_HOME"; clojure -A:native-image

      - name: Run upx
        run: upx fix-default-branch

      - uses: actions/upload-artifact@v2
        with:
          name: fix-default-branch-win64
          path: fix-default-branch
